### ISSUE TITLE
CORS Error in OpenAPI Spec Example

### ISSUE THREAD

**Issue by Shentoza** [haimkastner/unitsnet-js#39]
When trying to execute the OpenAPI Spec Example I'm getting a CORS issue.
![image](https://github.com/haimkastner/unitsnet-js/assets/7950966/99a32616-279d-47e3-886a-68ee1c50acef)

Specs:
- no vpn
- tested in Chrome & Edge

https://haimkastner.github.io/unitsnet-openapi-spec-example/

**Comment by haimkastner** [comment]
Hey @Shentoza,

I didn't mean to make it a "live" example, but just to demonstrate how the DTO is represented in the OpenAPI spec.

But... since you asked so nicely :) and it's extremely simple to do, I added it...

You can now make the call and get a real random DTO unit value representing (always) 10 meters.

Enjoy.
